// Tree-shakeable named exports — import only what you use.
export { BellIcon } from './icons/bell'
export { HeartIcon } from './icons/heart'
export { StarIcon } from './icons/star'
export { SearchIcon } from './icons/search'
export { WaveIcon } from './icons/wave'
export { SendIcon } from './icons/send'
export { DownloadIcon } from './icons/download'
export { TrashIcon } from './icons/trash'
export { ChatIcon } from './icons/chat'
export { KeyIcon } from './icons/key'
export { GitBranchIcon } from './icons/git-branch'
export { LayersIcon } from './icons/layers'
export { FunnelIcon } from './icons/funnel'
export { CartIcon } from './icons/cart'
export { MuscleIcon } from './icons/muscle'

export { useGesture } from './core/useGesture'
export type { GestureHandle, GestureTrigger } from './core/useGesture'
export type { GestureIconProps } from './core/types'
export * as easings from './core/easings'
