// Regenerates src/lib/index.ts from the files in src/lib/icons/.
// Run after adding icons: node scripts/gen-index.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const iconsDir = join(root, 'src/lib/icons')

const lines = []
for (const f of readdirSync(iconsDir).filter((f) => f.endsWith('.tsx')).sort()) {
  const src = readFileSync(join(iconsDir, f), 'utf8')
  const m = src.match(/export function (\w+Icon)/)
  if (!m) {
    console.warn(`skip ${f}: no exported *Icon function`)
    continue
  }
  lines.push(`export { ${m[1]} } from './icons/${f.replace(/\.tsx$/, '')}'`)
}

const out = `// Tree-shakeable named exports — import only what you use.
// GENERATED by scripts/gen-index.mjs — do not edit by hand.
${lines.join('\n')}

export { useGesture } from './core/useGesture'
export type { GestureHandle, GestureTrigger } from './core/useGesture'
export type { GestureIconProps } from './core/types'
export * as easings from './core/easings'
`
writeFileSync(join(root, 'src/lib/index.ts'), out)
console.log(`index.ts: ${lines.length} icons exported`)
